### ISSUE TITLE
Cannot find the required Google Proximity Beacon API

### ISSUE THREAD

**Issue by sweber6106** [google/beacon-platform#25]
The instructions specify three API's that must be included from the Google Developer Console.  Two of the API's are available, but the Google Proximity Beacon API is not.  The application can still be built, but it disappoints at runtime as follows:
<code>
2016-01-07 06:59:54.687 BeaconServiceDemoApp[4211:3217071] {
    "6e131d09 1c10a9a0 4f2c34b9 ab1cb791" =     {
        "error_message" = "Project has not enabled the API. Please use Google Developers Console to activate the 'proximitybeacon' API for your project.";
        "error_status" = "PERMISSION_DENIED";
    };
}
</code>

**Comment by sweber6106** [comment]
I managed to find the proximity API by searching (it does not seem to be listed) in the Developer Console.  I seem to be past all the setup, but the app cannot successfully scan:
<code>
2016-01-07 07:35:22.331 BeaconServiceDemoApp[4222:3222768] contents: {
  "error": {
    "code": 403,
    "message": "Unauthorized.",
    "status": "PERMISSION_DENIED"
  }
}
2016-01-07 07:35:22.335 BeaconServiceDemoApp[4222:3222768] response: <NSHTTPURLResponse: 0x19045b10> { URL: https://proximitybeacon.googleapis.com/v1beta1/beacons/3!6e131d091c10a9a04f2c34b9ab1cb791 } { status code: 403, headers {
    "Cache-Control" = private;
    "Content-Encoding" = gzip;
    "Content-Length" = 105;
    "Content-Type" = "application/json; charset=UTF-8";
    Date = "Thu, 07 Jan 2016 13:35:22 GMT";
    Server = ESF;
    Vary = "Origin, X-Origin, Referer";
    "alt-svc" = "quic=\":443\"; ma=604800; v=\"30,29,28,27,26,25\"";
    "alternate-protocol" = "443:quic,p=1";
    "x-content-type-options" = nosniff;
    "x-frame-options" = SAMEORIGIN;
    "x-xss-protection" = "1; mode=block";
} }
2016-01-07 07:35:22.336 BeaconServiceDemoApp[4222:3222768] error: (null)
2016-01-07 07:35:22.336 BeaconServiceDemoApp[4222:3222768] 0 1 1 1
2016-01-07 07:35:22.337 BeaconServiceDemoApp[4222:3222768] {
    "6e131d09 1c10a9a0 4f2c34b9 ab1cb791" =     {
        "error_message" = "Unauthorized.";

        "error_status" = "PERMISSION_DENIED";
    };
}
</code>

**Comment by marcwan** [comment]
Hey @sweber6106, thanks for the note!

So, the 403 is very much intended for that beacon — If you look in _FirstViewController.m_, where we list some "Fake" beacons, we include the beacon with ID `6e131d09 1c10a9a0 4f2c34b9 ab1cb7911` as an example of what happens when you ask for information about a beacon that's registered to somebody else.

The verbose output in the console might be confusing, but it's actually not showing any problem. (The iOS app currently prints _all_ REST API output, good or bad).

If the error message is nagging at ya though, feel free to just delete the code in _FirstViewController.m_ relating to `SHOW_SOME_FAKE_BEACONIDS_FOR_TESTING`.  

Sorry for the confusion!

**Comment by sweber6106** [comment]
Thanks for the quick response.  My application doesn't see the Eddystone
beacon that I created using a Node program so I'm trying to untangle that
and thought that the 403 might be a clue.  Thanks for the clarification.  I
do see my Node beacon from an app I downloaded though.  Curious.

BTW, I learned Node from your "Learning Node.js" and I recommend it to
others.  Thanks for the great book.
